name: Run Playwright Scraper and Post to n8n

on:
  workflow_dispatch:
    inputs:
      product_codes:
        description: "List of product codes as JSON array"
        required: true
        default: '["13699"]'

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (and Playwright)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and OS deps
        run: |
          python -m playwright install --with-deps chromium
          python -m playwright --version || true

      - name: Run scraper
        env:
          PRODUCT_CODES: ${{ github.event.inputs.product_codes }}
        run: |
          echo "PRODUCT_CODES=${PRODUCT_CODES}"
          python scrape_greenlight.py

      - name: Debug workspace (show files)
        run: |
          echo "PWD: $(pwd)"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la

      - name: Upload HTML files directly to n8n (no zip)
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
          PRODUCT_CODES: ${{ github.event.inputs.product_codes }}
        run: |
          set -euo pipefail

          # Ensure at least one matching HTML file exists
          if ! compgen -G "output_*.html" > /dev/null; then
            echo "ERROR: no output_*.html files found to upload."
            ls -la
            exit 1
          fi

          # Build curl args dynamically so we can attach every HTML file as a multipart field.
          # Use file[] as the field name (common convention). If your n8n expects a different
          # field name (e.g. file or files), change "file[]" below.
          curl_args=()
          for f in output_*.html; do
            [ -f "$f" ] || continue
            curl_args+=(-F "file[]=@${f}")
          done

          # Attach product_codes as a normal form field so n8n can access it.
          curl_args+=(-F "product_codes=${PRODUCT_CODES}")

          echo "Uploading ${#curl_args[@]} form fields to n8n webhook..."
          # Verbose to help debug in Action logs; the URL is stored in a secret so it won't be printed.
          curl -v -X POST "${curl_args[@]}" "${N8N_WEBHOOK_URL}"

      - name: Upload artifacts (safe fallback)
        uses: actions/upload-artifact@v4
        with:
          name: scraped-outputs
          path: |
            output_*.html
