name: Run Playwright Scraper

on:
  workflow_dispatch:
    inputs:
      product_codes:
        description: "List of product codes as JSON array"
        required: true
        default: '["13699"]'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        env:
          PRODUCT_CODES: ${{ github.event.inputs.product_codes }}
        run: python scrape_greenlight.py

      - uses: actions/upload-artifact@v4
        with:
          name: scraped-html
          path: output_*.html
          
      - name: Send result to n8n
        run: |
          zip -r output.zip scraped_pages/
          curl -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "file=@output.zip" \
            -F "product_codes=${{ github.event.inputs.product_codes }}" \
            ${{ secrets.N8N_WEBHOOK_URL }}

