name: Run Playwright Scraper and Send Results via Gmail

on:
  workflow_dispatch:
    inputs:
      product_codes:
        description: "List of product codes as JSON array"
        required: true
        default: '["13699"]'

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (and Playwright)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and OS deps
        run: |
          python -m playwright install --with-deps chromium
          python -m playwright --version || true

      - name: Run scraper
        env:
          PRODUCT_CODES: ${{ github.event.inputs.product_codes }}
        run: |
          echo "PRODUCT_CODES=${PRODUCT_CODES}"
          python scrape_greenlight.py

      - name: Debug workspace (show files)
        run: |
          echo "PWD: $(pwd)"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la

      - name: Upload artifacts (safe fallback)
        uses: actions/upload-artifact@v4
        with:
          name: scraped-outputs
          path: |
            output_*.txt

      - name: Send aggregated TXT via Gmail
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          # Optional: RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          set -euo pipefail

          python -m pip install --upgrade pip
          python -m pip install requests

          echo "Repository files (for debug):"
          ls -la

          # Show the files we're about to aggregate (debug only)
          ls -la output_*.txt || true

          # Run the email sender. Ensure the script is at scripts/email_results.py
          python email_results.py
