name: Run Playwright Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python scrape_greenlight.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scraped-output
          path: |
            output.html
            page_before_login.png
            page_after_login.png
